### ISSUE TITLE
About diff between SingleNet and ADDBNet

### ISSUE THREAD

**Issue by kimkyeonghun** [addb-swstarlab/addb_tuning#1]
I want to know difference betweent SingleNet and ADDBNet.

I think ADDBNet is just multiple SingleNet using with Late-fusion.

What are the advantages of this fusion method(Late-Fusion)?

**Comment by JIEUN-12** [comment]
The main difference is not late-fusion in ADDBNet.
ADDBNet is designed for using pre-trained weights of each DBMS, such as redis, rocksdb and spark.

Because of this method, we should use Late-Fusion.

Thank you.
