### ISSUE TITLE
About optimization method.

### ISSUE THREAD

**Issue by hello-maker** [addb-swstarlab/addb_tuning#2]
Hi 
Among the various optimization algorithms, why did you use the genetic algorithm?
Moreover, Were comparative experiments conducted with other optimization algorithms?

Thank you!!

**Comment by JIEUN-12** [comment]
Other algorithms can be fully applicable. The reason that we have chosen the genetic algorithm is that there is a less high-dimensional problem than BO which is commonly used in this domain.

We do not plan to conduct comparative experiments.

Thanks for your interest!
