### ISSUE TITLE
Is the data path on line 126 of dbminfos.py correct?

### ISSUE THREAD

**Issue by HwanheeKim813** [addb-swstarlab/addb_tuning#3]
In this part, is there a reason to use addb_config? Or is it a typo?
https://github.com/addb-swstarlab/addb_tuning/blob/d968539d918fe1fbd6b9f9b01f2dffe1300f898f/dbmsinfos.py#L126

**Comment by JIEUN-12** [comment]
The command is for reading config files that we generated before. Therefore, "addb_config" is just the name of our generated sample files. 

You can also change the name on your own.

I hope that my answer was helpful.

**Comment by HwanheeKim813** [comment]
Thank you for your answer. I have wrong understood. I just looked at a data information.
